[package]
name = "rsa-keygen"
version = "0.1.0"
edition = "2021"

[dependencies]
rsa-core = { path = "../rsa-core" }
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
rand="0.8"
